org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# ------------------------------------------------------------------
# اگر دانلود کتابخانه‌ها از سرورهای گوگل برایت کار نمی‌کند،
# این را true کن تا از یک آینه داخلی گرفته شوند.
# ------------------------------------------------------------------
useIranMirror=false
